### ISSUE TITLE
User endpoints creation

### ISSUE THREAD

**Issue by pearlescence-m** [larkinds/recurse-randomice#37]
**Overview**

We need endpoints that allow users to create an account and login into it. 

**Action Items**

- [x] Add a MongoDB schema file to the `/models` folder
- [x] Create user router file in `/controllers` folder
- [x] POST endpoint to create user
- [x] POST endpoint to login

**Resources/Instructions**
[Schema in Notion](https://www.notion.so/DB-Schemas-and-backend-80d260ccbc4c4f98a0edab26bdd3f5ad)

**Comment by fesimaxu** [comment]
Hey, I am interested in working on the backend of the project using node js
To create the user authentication endpoints of login and signup
Jsonwebtoken as authorization
mongoDB as database
