### ISSUE TITLE
Components: User-Generated Flavor Page

### ISSUE THREAD

**Issue by eyeriss42** [larkinds/recurse-randomice#45]
Overview

User can click on "Generate Your Own Flavor" button. The user is prompted to a "slot machine" and can save a flavor if they like it, both on their profile page and hall of fame. The user can add newly generated-flavor to cart.

Action Items

- [ ] create a wireframe for a user-generated flavor creation
- [ ] create the UI for flavor creation (based on a wireframe)

Resources/Instructions

You can find the wireframe on [Notion](https://www.notion.so/User-Generated-Flavor-b3ec18b3677b440f9dfe01e2a0585428?pvs=4).

**Comment by meru-a** [comment]
Adding this to the home page!
